package app.View.Compras;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author DevTARDE A
 */
public class TeladeCompras extends javax.swing.JFrame {

    /**
     * Creates new form TeladeCompras
     */
    public TeladeCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1ConcCompras = new javax.swing.JPanel();
        jLabel1TextoLogo = new javax.swing.JLabel();
        jPanelFormaPag = new javax.swing.JPanel();
        jComboBoxPagamentos = new javax.swing.JComboBox<>();
        jButton1FinVend = new javax.swing.JButton();
        jButton3CancelVend = new javax.swing.JButton();
        jPanel1ProdTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelResumVend = new javax.swing.JPanel();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldCódVend = new javax.swing.JTextField();
        jTextFieldCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(830, 600));
        setMinimumSize(new java.awt.Dimension(830, 600));
        setPreferredSize(new java.awt.Dimension(830, 600));
        getContentPane().setLayout(null);

        jPanel1ConcCompras.setMaximumSize(new java.awt.Dimension(830, 600));
        jPanel1ConcCompras.setMinimumSize(new java.awt.Dimension(830, 600));
        jPanel1ConcCompras.setName(""); // NOI18N
        jPanel1ConcCompras.setPreferredSize(new java.awt.Dimension(830, 600));
        jPanel1ConcCompras.setLayout(null);

        jLabel1TextoLogo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1TextoLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1TextoLogo.setText("CONCLUSÃO DE COMPRAS");
        jPanel1ConcCompras.add(jLabel1TextoLogo);
        jLabel1TextoLogo.setBounds(305, 18, 227, 25);

        jPanelFormaPag.setBorder(javax.swing.BorderFactory.createTitledBorder("FORMA DE PAGAMENTO"));
        jPanelFormaPag.setMaximumSize(new java.awt.Dimension(283, 270));

        jComboBoxPagamentos.setBackground(new java.awt.Color(242, 242, 242));
        jComboBoxPagamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MÉTODO DE PAGAMENTO: ", "PIX ", "DINHEIRO  ", "CARTÃO DE CRÉDITO ", "CARTÃO DE DÉBITO ", "FIADO? " }));

        jButton1FinVend.setBackground(new java.awt.Color(0, 153, 51));
        jButton1FinVend.setText("FINALIZAR VENDA ");
        jButton1FinVend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1FinVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1FinVendActionPerformed(evt);
            }
        });
        jButton1FinVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1FinVendKeyPressed(evt);
            }
        });

        jButton3CancelVend.setBackground(new java.awt.Color(204, 0, 0));
        jButton3CancelVend.setText("CANCELAR VENDA");
        jButton3CancelVend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3CancelVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3CancelVendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormaPagLayout = new javax.swing.GroupLayout(jPanelFormaPag);
        jPanelFormaPag.setLayout(jPanelFormaPagLayout);
        jPanelFormaPagLayout.setHorizontalGroup(
            jPanelFormaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormaPagLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelFormaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormaPagLayout.createSequentialGroup()
                        .addGroup(jPanelFormaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3CancelVend, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1FinVend, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormaPagLayout.createSequentialGroup()
                        .addComponent(jComboBoxPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelFormaPagLayout.setVerticalGroup(
            jPanelFormaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormaPagLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBoxPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1FinVend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton3CancelVend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1ConcCompras.add(jPanelFormaPag);
        jPanelFormaPag.setBounds(530, 50, 290, 270);

        jPanel1ProdTable.setBorder(javax.swing.BorderFactory.createTitledBorder("PRODUTOS "));

        jTable1.setBackground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓD PRODUTO", "PRODUTO", "QUANTIDADE", "VALOR"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1ProdTableLayout = new javax.swing.GroupLayout(jPanel1ProdTable);
        jPanel1ProdTable.setLayout(jPanel1ProdTableLayout);
        jPanel1ProdTableLayout.setHorizontalGroup(
            jPanel1ProdTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1ProdTableLayout.setVerticalGroup(
            jPanel1ProdTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        jPanel1ConcCompras.add(jPanel1ProdTable);
        jPanel1ProdTable.setBounds(10, 340, 810, 250);

        jPanelResumVend.setBorder(javax.swing.BorderFactory.createTitledBorder("RESUMO DA VENDA"));
        jPanelResumVend.setMaximumSize(new java.awt.Dimension(490, 270));
        jPanelResumVend.setMinimumSize(new java.awt.Dimension(490, 270));
        jPanelResumVend.setPreferredSize(new java.awt.Dimension(490, 270));

        jTextFieldPreco.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldPreco.setBorder(javax.swing.BorderFactory.createTitledBorder("PREÇO"));

        jTextFieldCódVend.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldCódVend.setBorder(javax.swing.BorderFactory.createTitledBorder("CÓD VENDA"));

        jTextFieldCliente.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("CLIENTE"));

        javax.swing.GroupLayout jPanelResumVendLayout = new javax.swing.GroupLayout(jPanelResumVend);
        jPanelResumVend.setLayout(jPanelResumVendLayout);
        jPanelResumVendLayout.setHorizontalGroup(
            jPanelResumVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumVendLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelResumVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResumVendLayout.createSequentialGroup()
                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelResumVendLayout.createSequentialGroup()
                        .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jTextFieldCódVend, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanelResumVendLayout.setVerticalGroup(
            jPanelResumVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumVendLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelResumVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCódVend, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1ConcCompras.add(jPanelResumVend);
        jPanelResumVend.setBounds(10, 50, 510, 270);

        getContentPane().add(jPanel1ConcCompras);
        jPanel1ConcCompras.setBounds(0, 0, 830, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1FinVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1FinVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FinVendActionPerformed

    private void jButton3CancelVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3CancelVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3CancelVendActionPerformed

    private void jButton1FinVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1FinVendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FinVendKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeladeCompras().setVisible(true);
            }
        });
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1FinVend;
    private javax.swing.JButton jButton3CancelVend;
    private javax.swing.JComboBox<String> jComboBoxPagamentos;
    private javax.swing.JLabel jLabel1TextoLogo;
    private javax.swing.JPanel jPanel1ConcCompras;
    private javax.swing.JPanel jPanel1ProdTable;
    private javax.swing.JPanel jPanelFormaPag;
    private javax.swing.JPanel jPanelResumVend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldCódVend;
    private javax.swing.JTextField jTextFieldPreco;
    // End of variables declaration//GEN-END:variables
}
