
package app.View;

import javax.print.DocFlavor.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.tools.Tool;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import app.Controller.LoginController;

/**
 *
 * @author igorf and Edu
 */
public class TelaDeInicio extends javax.swing.JFrame {


    /**
     * Creates new form TelaDeInicio
     */
    public TelaDeInicio() {
        super("Home");
        initComponents();
        setIcon();
       
    }

    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("./resources/i.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        inputSenha = new javax.swing.JPasswordField();
        inputEmail = new javax.swing.JFormattedTextField();
        btnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
    
      
        setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(830, 600));
        getContentPane().setLayout(null);
        getContentPane().add(inputSenha);
        inputSenha.setBounds(480, 310, 170, 30);
        getContentPane().add(inputEmail);
        inputEmail.setBounds(480, 240, 170, 30);

        btnEntrar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(520, 360, 130, 27);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/View/resources/Design sem nome (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 550);

        pack();

        btnEntrar.addActionListener(e -> {
            LoginController operacao = new LoginController();
            String usuario = inputEmail.getText();
            String senha = inputSenha.getText();
        
            boolean loginRealizado = false;
        
            // Verifica o login como gerente
            operacao.verificaLogin(usuario, senha, "gerente");
            
            // Verifica se o usuário é gerente após a tentativa de login
            if (operacao.isGerente()) {
                dispose();
                new app.View.Hierarquia.JanelaGerente().setVisible(true);


                loginRealizado = true;
            }
        
            // Se não foi realizado o login como gerente, tenta como caixa
            if (!loginRealizado) {
                operacao.verificaLogin(usuario, senha, "caixa");
        
                // Verifica se o usuário é caixa após a tentativa de login
                if (operacao.isCaixa()) {
                    dispose();
                    new app.View.Hierarquia.JanelaCaixa().setVisible(true);
                    //TelaDeInicio.dispose();
                    loginRealizado = true;
                }
            }
        
            
        });

    
        
        
        
         

    }


//dudu parts  


 



    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JFormattedTextField inputEmail;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}